### ISSUE TITLE
chamfer2D or chamfer_dist

### ISSUE THREAD

**Issue by SchwarzSolomon** [Golriz-code/shellGeneration#5]
I am reproducing PoinTr and your shellGeneration method. I have a question about the 'extensions' folder in your code. In the 'extension' folder, there is a file called 'chamfer2D', but in your 'models/PoinTr.py' file, on line 5, you use 'extensions.chamfer_dist'. I would like to know which extension exactly you are using.

**Comment by Golriz-code** [comment]
Hello,
Sorry for the late response. I tried with different ones, but for the paper, we used "extensions.chamfer_dist".
